### ISSUE TITLE
[Enhancement] Use tags instead of item IDs where appropriate.

### ISSUE THREAD

**Issue by Vaelzan** [Noobulus/Tetra-Pak#10]
There are a number of cases where changing from using a specific item ID to a tag would automatically add compatibility with several new mods.

For example, if Arcane Gold was to use the `forge:ingots/arcane_gold` tag, the material would be compatible with the Arcane Gold from both Eidolon and Forbidden and Arcanus.

Similarly, `forge:ingots/pewter`, `forge:ingots/brass`, and `forge:gems/moonstone` all have tags included in their respective mods.

**Comment by Noobulus** [comment]
This has been fixed for a while, just forgot to close the issue.
