### ISSUE TITLE
Some materials show as if they are work in progress.

### ISSUE THREAD

**Issue by Kazzc** [Noobulus/Tetra-Pak#11]
For an example. . . Shadow steel can be used as a blade material but says is a work in progress. (I am assuming this is from standard tetra and not your mod itself)
![image](https://user-images.githubusercontent.com/48134871/137569391-b744e73d-bf18-4fcc-bc3b-3f36156d5f45.png)
Granted, you can still use said material to craft the blade regardless.

**Comment by Noobulus** [comment]
That text is from Create, the mod that adds that material. It's talking about usages in Create, not in Tetra Pak. As such, it has no bearing on Tetra Pak's features and can be ignored.
