### ISSUE TITLE
Server Connection Error

### ISSUE THREAD

**Issue by watermelon0guy** [Noobulus/Tetra-Pak#13]
Players cannot connect to the server. Without this addon, the server starts. [https://pastebin.com/drs8fhmp](url)
`Internal Exception: io.netty.handler.codec.EncoderException: net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: field_186466_c`

**Comment by Noobulus** [comment]
Pastebin says that the log you attached is private or pending moderation. Uploading it to a similar site or adjusting privacy settings should fix that so I can view it. I'll try and recreate the issue on my side soon for debugging.

**Comment by watermelon0guy** [comment]
https://disk.yandex.ru/d/-olVSm3nZLFD4g
Apologize. Here is the link to download txt. If necessary, I can send my entire server and mods from the client (so that you don't download everything separately)

**Comment by Noobulus** [comment]
I believe this has been fixed in [6ce6d7f](https://github.com/Noobulus/Tetra-Pak/commit/6ce6d7fa66cfa6216db9f7e1d46559d625441649), but I'll leave the issue open until I've published a new version to CurseForge for you to test.

**Comment by watermelon0guy** [comment]
Thanks, everything works now
