### ISSUE TITLE
Crossbow damage sometimes causes a crash

### ISSUE THREAD

**Issue by watermelon0guy** [Noobulus/Tetra-Pak#16]
https://www.toptal.com/developers/hastebin/yecudohuze
"I do not know why, I do not know why" but sometimes (every 3-4 shots) when I shoot mobs with a crossbow, the server crashes
PS: new crash https://www.toptal.com/developers/hastebin/lizecuyawo

**Comment by Noobulus** [comment]
This should be fixed in [ea2295f](https://github.com/Noobulus/Tetra-Pak/commit/ea2295f886a0d22a79b8d4f3feb76d909ff165fb). Didn't mean to close this, sorry!

**Comment by Noobulus** [comment]
Should be fixed in [Tetra Pak 1.4.3](https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3726132). Thanks for reporting and bearing with me as I fix all the porting bugs I missed. :P

**Comment by watermelon0guy** [comment]
Thx!
