### ISSUE TITLE
Game crash when using refined radiance axe.

### ISSUE THREAD

**Issue by alexandermeek** [Noobulus/Tetra-Pak#2]
When I try to use the refined radiance material on an axehead and then break anything, not just trees, the game just crashes immediately. Not entirely sure what is the cause, the deforester from create seems to work just fine.
Crash report:[https://pastebin.com/ewxVUM4s](url)

**Comment by Noobulus** [comment]
This is no longer an issue as of 0.2. This bug is caused by Tetra Pak not being able to access a version of Create's Deforester code that was changed as of 0.3.1b. 0.2 uses the new code and should no longer have this problem. Thanks for reporting!
