### ISSUE TITLE
refined radiance tools don't have a special ability

### ISSUE THREAD

**Issue by lag42** [Noobulus/Tetra-Pak#3]
in tetrapak 0.2 refined radiance tools seem to be lacking their trait that makes them mine multiple blocks, making them not all that special aside from being extremely slow

**Comment by SpottyTheTurtle** [comment]
have you tried the refined radience axe?

**Comment by Noobulus** [comment]
This issue has been fixed and the patch has been released. Download the updated version and report back if the issue persists.
[https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3328381](https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3328381)

**Comment by lag42** [comment]
the updated version does indeed fix this
