### ISSUE TITLE
Moonstrike Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Noobulus/Tetra-Pak#4]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Tetra Pak v0.2.2`

After trying to join the server, my server crashed. It seems to be related to arrows and the Moonstrike effect.
[Crash Report](https://gist.github.com/WenXin20/200c7debe5038145ce1069a4defe102c)

**Comment by LordGrimmauld** [comment]
should be fixed in 381297f
therefore we hope to be able to close this issue after release

**Comment by WenXin20** [comment]
Thanks!

**Comment by Noobulus** [comment]
Fixed in [latest release](https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3386285). Thanks for reporting!
