### ISSUE TITLE
tetrapak-1.16.5-0.3.1 - multiplayer/PlayerController for invalid dist DEDICATED_SERVER Crash

### ISSUE THREAD

**Issue by DeltaWolf7** [Noobulus/Tetra-Pak#7]
Forge: 36.2.1
Minecraft: 1.16.5
Tetrapak: 0.3.1

Full Log: https://pastebin.com/16rBx618

Hi,

Tetrapak 0.3.1 crashes on server startup with the new version. Above it the full details.

Thanks

**Comment by LordGrimmauld** [comment]
Hi,
This should be fixed in 03d8663 and public on next curseforge release.
Thanks for reporting

**Comment by LordGrimmauld** [comment]
Alright, the release is out at https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3401450
I'll close this issue, reopen if it persists
