### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Drakoflame** [Noobulus/Tetra-Pak#9]
I had hopeful wishes that things would work smoothely after the new Tetra update, but I figured things would be busted. I saw the other issue report about a crash with Druidcraft, and that you're already working on an update, but I figured I'd throw in my crash report in the hopes that it helps with anything that might have been missed!

https://pastebin.pl/view/66436f64

**Comment by Noobulus** [comment]
This should be fixed in the [latest release](https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3456988). Thanks for reporting!
